### ISSUE TITLE
What to do in cases where a command is missed? 

### ISSUE THREAD

**Issue by ideal2545** [nagyrobi/home-assistant-custom-components-cover-rf-time-based#17]
Hi I randomly have a situation where a command is missed by a cover (window blind), not really sure what to do in this case, should I alter the script to send multiple rfraw commands to try and compensate?

**Comment by nagyrobi** [comment]
That's mostly because of RF interference in that area. I'd first try re-locating the RF bridge somewhere closer to the blind, or check the antenna wire of the blind itself, not to be too close to metallic surfaces.
