### ISSUE TITLE
No cover.set_cover_position after Update to newest HassOS core-2021.3.1

### ISSUE THREAD

**Issue by mcfly2283-ai** [nagyrobi/home-assistant-custom-components-cover-rf-time-based#19]
After the Update to newest HassOS and Integration, the cover.set_cover_position won`t work anymore for me.
After Setting the Position manually to 50, nothing happens, but the Entity says Its Done. Im Using it with custom.entity.slider.row

Setting:

service: cover.set_cover_position
target:
  entity_id: cover.kuche_rollo
data:
  position: 50

resulting in:

current_position: 50
travelling_time_down: 17
travelling_time_up: 18
unconfirmed_state: 'True'
friendly_name: Küche Rollo
assumed_state: true
supported_features: 15

Nothing is happing in real. Only the Cover-Buttons "up" Down" "Stop" are working right now within the UI.
The Scripts for MQTT publish to Sonoff Tasmota-Bridge are tested and working fine. No Errors in Log.
I cant`t say if it is a Problem with HA or with rf-Integration. It seems that the postions are reversed 
right now: "0" is opened and "100" is closed.

Configuration.yaml

  - platform: cover_rf_time_based
    devices:
        kueche_cover_time_based:
          name: Küche Rollo
          travelling_time_up: 18
          travelling_time_down: 17
          close_script_entity_id: script.rollo_kuche_down
          stop_script_entity_id: script.rollo_kuche_stop
          open_script_entity_id: script.rollo_kuche_up

Script:

service: mqtt.publish
data:
  topic: cmnd/RFBridge_Tasmota/backlog
  payload: >-
    RfRaw
    AAB035050812DE05F0017202D02BC0481XXXXXXXXXXXXA3B2A3A3A3B2A3B2A3A3B2A3B2A3A3B2B2B2A3A3A3B2A3A3A3A3B2B2B2B2A3A55

**Comment by barmazu** [comment]
I have updated to "2021.2.3" (so last Feb update) and I'm seeing the same - all seems to be reverted. 
However at the same time I have updated to 1.0.4 (from 1.14a)
Looking at changes it seems to be related with changes in custom_components/cover_rf_time_based/manifest.json exactly a xknx updated to 0.17.1. Workaround would be to revert this back 0.9.4 and restart HA to restore old behavior.

**Comment by nagyrobi** [comment]
Fixed, thanks

**Comment by mcfly2283-ai** [comment]
Works like a charm! Thank you
