### ISSUE TITLE
Position value inconsistent with Home Assistant Template Cover convention

### ISSUE THREAD

**Issue by usul0184** [nagyrobi/home-assistant-custom-components-cover-rf-time-based#22]
I think merging pull request #21 may have caused some unexpected behavior.  The merge flipped the meaning of position 0 from closed to open and position 100 from open to closed.  The problem is that Home Assistant uses the former convention, as seen in its [Template Cover documentation](https://www.home-assistant.io/integrations/cover.template/#position_template).  If you use a Cover Time Based Component within a Template Cover, things go awry unless you manually flip the positions back to the former convention.

Great component, and thanks for all your work!

**Comment by nagyrobi** [comment]
I'm considering to revert the patch.

**Comment by nagyrobi** [comment]
Reverted.
