### ISSUE TITLE
Please add the config variable unique_id 

### ISSUE THREAD

**Issue by keteflips** [nagyrobi/home-assistant-custom-components-cover-rf-time-based#27]
To allow configuration  through the Home Assitant UI this variable it's necessary.

Please add it.

Thanks.

**Comment by nagyrobi** [comment]
This component doesn't support configuration through UI.

**Comment by keteflips** [comment]
I need this option to add the area of the cover.
Then, it's possible to add the area parameter?

Thanks for your work.

**Comment by nagyrobi** [comment]
What's the importance of the area of the cover?

**Comment by nagyrobi** [comment]
Fixed in https://github.com/nagyrobi/home-assistant-custom-components-cover-rf-time-based/commit/de84c037242fbad6de4f9984d45a97985f7d9818
