### ISSUE TITLE
Buttons stay active if cover reached end position

### ISSUE THREAD

**Issue by VDRainer** [nagyrobi/home-assistant-custom-components-cover-rf-time-based#3]
If the cover is in position 0% or 100% the buttons for up down stay active and also call the scripts.
So if the cover fully open, the up button should be inactive and not call the up script.

**Comment by nagyrobi** [comment]
I can't reproduce this. Please share your config and scripts.

**Comment by nagyrobi** [comment]
I see in your other issue that you're using relays. This component is more for triggers without feedback, try using the original component: https://github.com/davidramosweb/home-assistant-custom-components-cover-time-based

**Comment by nagyrobi** [comment]
Duplicate of https://github.com/nagyrobi/home-assistant-custom-components-cover-rf-time-based/issues/2
