### ISSUE TITLE
using cover object instead of scripts/switches

### ISSUE THREAD

**Issue by capi92** [nagyrobi/home-assistant-custom-components-cover-rf-time-based#35]
Hi,

I'm having RFXTRX for Somfy RTS shutter.
RFXTRX integration create cover objects.

In order to have this custom component to work, I need to create via script the cover command open, close and stop.
Would it be possible to support also cover objects ? 
It looks a little bit weird to create manual command for an already existing cover to make it working.

Thanks,
Pierre

rfxtrx:
  device: /dev/ttyUSB1
  devices:
    # cover.bureau     
    xxxxxxxxxxxxxxx: 

cover:
  - platform: cover_rf_time_based
    devices:
      shutter_bureau:
        name: Volet roulant du bureau
        travelling_time_up: 28
        travelling_time_down: 26
        close_script_entity_id: script.close_shutter_bureau
        stop_script_entity_id: script.stop_or_my_shutter_bureau
        open_script_entity_id: script.open_shutter_bureau
        send_stop_at_ends: False #optional
        aliases:
          - volet_roulant_du_bureau

//script file

'open_shutter_bureau':
  alias: 'Ouvre le volet du bureau'
  sequence:
    - service: cover.open_cover
      data:
        entity_id: cover.bureau
        #option: open

'close_shutter_bureau':
  alias: 'Ferme le volet du bureau'
  sequence:
    - service: cover.close_cover
      data:
        entity_id: cover.bureau
        #option: closed

'stop_or_my_shutter_bureau':
  alias: 'Fixe le volet du bureau'
  sequence:
    - service: cover.stop_cover
      data:
        entity_id: cover.bureau
        #option: stop

**Comment by nagyrobi** [comment]
It's like this by design.

**Comment by nagyrobi** [comment]
check latest release

**Comment by capi92** [comment]
Thanks, will test next week.
