### ISSUE TITLE
Integration breaks built-in KNX integration

### ISSUE THREAD

**Issue by marvin-w** [nagyrobi/home-assistant-custom-components-cover-rf-time-based#50]
Hello,

we recently had a bug report in HA core (https://github.com/home-assistant/core/issues/76604) mentioning that a very old xknx version is used to run the KNX integration. After some analysis the issue creator found out that this custom integration is using xknx==0.9.4, which is from 3 years ago as a pinned dependency.

Can you please update to the latest version of xknx or even better - get rid of it altogether.

**Comment by nagyrobi** [comment]
You're more than welcome to suggest a patch in a PR...

**Comment by farmio** [comment]
You may just copy this file (or an older version if you prefer) to this repo, remove the requirement and import `from .` instead of `form xknx.devices`. 
https://github.com/XKNX/xknx/blob/main/xknx/devices/travelcalculator.py

**Comment by nagyrobi** [comment]
Thank you both for the issue sumbission and permission to use the code as copied.
Removed dependency in https://github.com/nagyrobi/home-assistant-custom-components-cover-rf-time-based/commit/cd0851157601554d29e4b5b6f216df5cb3ce136d and released a new version which can be upgraded to via HACS.

**Comment by marvin-w** [comment]
Thank you for fixing it so fast :)

**Comment by nagyrobi** [comment]
Was easy with @farmio's suggestion.
