### ISSUE TITLE
Can't reset inconsistent position

### ISSUE THREAD

**Issue by fredericks1982** [nagyrobi/home-assistant-custom-components-cover-rf-time-based#8]
Cover state is assumed, so sometimes the Home Assistant cover status could be inconsistent with the real situation (for instance if someone used the old RF remote instead of using HA, or if the RF receiver fails before of bad quality signal).
I didn't found a way to "reset" the position to its actual value, i.e. overriding the cover position value in HA without sending any RF signal to the cover. Is there some special parameter or service to do that? Now I have to manually call my RF script to completely open the cover and then call the `cover.open_cover` service to align the HA position value to the actual position of the cover: it would be much more elegant to have some `cover.reset_position` to do the same

**Comment by PLTorrent** [comment]
Hi, I think the easiest way to reset is when you have the cover fully opened or closed send open or close signal and just wait for the slider to get to the position. I just did that and worked like a charm. Since the cover is already at min/max position it will not move anyway.
