### ISSUE TITLE
[Feature Request] Sunshade/Marquis mode

### ISSUE THREAD

**Issue by PLTorrent** [nagyrobi/home-assistant-custom-components-cover-rf-time-based#9]
Hi, 
As a feature request it would be nice to add Sunshade/Marquis mode which would basically reverse the directions of operation. By intuition sunshade is closed when it is rolled up and it is open when it rolls down and creates shade.  Of course one can swap the RF codes but the position slider will go the wrong way

**Comment by nagyrobi** [comment]
This has been requested many times, it's not compnent dependent. Home Assistant internals work like that.

**Comment by nagyrobi** [comment]
Done: https://github.com/nagyrobi/home-assistant-custom-components-cover-rf-time-based/pull/21
